name: Sync upstream

on:
  schedule:
    - cron: "*/30 * * * *"  # hver 30. minut
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/iotku/mumzic.git || true
          git fetch upstream

      - name: Merge upstream into default branch
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          git checkout "$BRANCH"
          git merge --no-edit "upstream/$BRANCH" || (git merge --abort && exit 0)

      - name: Push changes (if any)
        run: |
          git push
